### PR TITLE
Add OWF C binary implementation

### PR DESCRIPTION
**Pull request by mjones-mic**
Add a C implementation for the OWF binary unpacker.

### CODE REVIEW

**Comment by crertel** [comment]
Visual Studio projects?

**Comment by mjones-mic** [comment]
@crertel not yet, but I'll just add those commits to this pull when they're finished

**Comment by mjones-mic** [comment]
7570796ec6227a04a4b093d669d92ed04f6389b1 addresses #6

**Comment by mjones-mic** [comment]
@crertel tests green on Windows, sir!

**Pull request merged**
